#pragma once

#include <windows.h>

constexpr UINT WM_DICTATOR_TRAY = WM_APP + 1;

constexpr int ID_DICTATOR_HOTKEY = 1001;

constexpr UINT IDM_DICTATOR_TEST_INSERT = 40001;
constexpr UINT IDM_DICTATOR_SHOW_STATUS = 40002;
constexpr UINT IDM_DICTATOR_SET_RIGHT_ALT = 40003;
constexpr UINT IDM_DICTATOR_SET_F8 = 40004;
constexpr UINT IDM_DICTATOR_SET_CTRL_ALT_SPACE = 40005;
constexpr UINT IDM_DICTATOR_CLEAR_HOTKEY = 40006;
constexpr UINT IDM_DICTATOR_EXIT = 40007;
